base_url = "/"
build_search_index = true
compile_sass = true
default_language = "en"
minify_css = true
minify_html = true
minify_js = true
theme = "wildman"
title = "ryanwild.com"

[markdown]
external_links_no_follow = true
external_links_no_referrer = true
external_links_target_blank = true
highlight_code = true
highlight_theme = "ayu-dark"
render_emoji = false
smart_punctuation = false


[extra]
favicon = "/favicon.ico"
mathjax = false
theme = "toggle" # light, dark, auto, toggle
toc = true
use_cdn = false

stylesheets = [
    "extra.css"
]

copyright_date = 2024

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    # { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "GitHub", url = "https://github.com/ryanwild/", icon = "github" },
]

custom_css = []

[extra.analytics]
enabled = false

# [extra.analytics.goatcounter]
# user = "your_user"
# host = "example.com"    # default= goatcounter.com

# [extra.analytics.umami]
# website_id = "43929cd1-1e83...."
# host_url = "https://stats.mywebsite.com" # default: https://analytics.eu.umami.is
