name = "ryanwild.com"
description = "Personal theme of Ryan Wild"
version = "0.0.1"
license = "MIT"
homepage = "https://github.com/ryanwild/wildman"
demo = "https://ryanwild.github.io/wildman"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[author]
name = "Ryan Wild"
homepage = "https://ryanwild.com"
